version: "3"

services:
  db:
    image: postgres:12
    volumes:
      - db_volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - ${HOME}/.ssh:/home/vscode/.ssh
      - ${HOME}/.gitconfig:/home/vscode/.gitconfig
      - ./jupyter_notebook_config.py:/home/vscode/.jupyter/jupyter_notebook_config.py
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
volumes:
  db_volume:
